name: EMA Live Paper (loop AM)

on:
  schedule:
    # 13:30 UTC ≈ 6:30 PT (cron is UTC)
    - cron: "30 13 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ema-live-paper-loop-am
  cancel-in-progress: true

jobs:
  trade:
    runs-on: [self-hosted, windows]
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v4

      - name: Ensure Python path
        shell: pwsh
        run: |
          $python = (Get-Command python.exe).Source
          echo "PYTHON_EXE=$python" >> $env:GITHUB_ENV

      - name: Install deps
        shell: pwsh
        run: |
          & "$env:PYTHON_EXE" -m pip install --upgrade pip
          & "$env:PYTHON_EXE" -m pip install -r EMAMerged/requirements.txt

      - name: Run market loop (paper trading)
        shell: pwsh
        env:
          # ✅ Correct envs your code actually reads
          APCA_BASE_URL: https://paper-api.alpaca.markets
          APCA_API_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}

          # (Optional) back-compat aliases also understood by your code
          ALPACA_KEY:   ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET:${{ secrets.ALPACA_SECRET_KEY }}

          # Control flags
          DRY_RUN:  "0"
          FORCE_RUN: "0"

          PYTHONUNBUFFERED: "1"
        run: |
          chcp 65001 > $null
          echo "PYTHONPATH=$env:GITHUB_WORKSPACE" >> $env:GITHUB_ENV
          & "$env:PYTHON_EXE" -X utf8 -u EMAMerged/scripts/market_loop.py
