name: EMA Live Paper (AM loop, self-hosted Windows)

on:
  workflow_dispatch:
    inputs:
      tickers:
        description: "Comma-separated symbols (blank = EMAMerged/tickers.txt)"
        required: false
        default: ""
      dry_run:
        description: "1=log only, 0=live"
        required: false
        default: "1"
      force_run:
        description: "1=bypass market-hours gate"
        required: false
        default: "0"
      adx:
        description: "Override ADX threshold (blank=default)"
        required: false
        default: ""
      rsi_min:
        description: "Override RSI min (blank=default)"
        required: false
        default: ""
      rsi_max:
        description: "Override RSI max (blank=default)"
        required: false
        default: ""
      slope_pct:
        description: "Override EMA9 slope pct (e.g. 0.0012)"
        required: false
        default: ""
  schedule:
    - cron: "*/5 13-20 * * 1-5"

jobs:
  live:
    runs-on: [self-hosted, windows]
    timeout-minutes: 15
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4

      - name: Resolve Python (absolute path)
        run: |
          $candidates = @(
            "C:\Users\vraoo\AppData\Local\Programs\Python\Python313\python.exe",
            "C:\Program Files\Python313\python.exe",
            "C:\Program Files\Python311\python.exe"
          )
          $py = $null
          foreach ($p in $candidates) { if (Test-Path $p) { $py = $p; break } }
          if (-not $py) { throw "Python not found. Adjust candidates." }
          echo "PYTHON_EXE=$py" >> $env:GITHUB_ENV
          & "$py" --version

      - name: Install deps
        run: |
          & "$env:PYTHON_EXE" -m pip install --upgrade pip
          & "$env:PYTHON_EXE" -m pip install -r EMAMerged/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$env:GITHUB_WORKSPACE" >> $env:GITHUB_ENV

      - name: Run live loop once
        env:
          # Alpaca
          ALPACA_API_KEY:    ${{ secrets.ALPACA_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_SECRET }}
          ALPACA_BASE_URL:   ${{ secrets.ALPACA_BASE_URL }}

          # Overrides (optional)
          FILTER_ADX:        ${{ github.event.inputs.adx }}
          FILTER_RSI_MIN:    ${{ github.event.inputs.rsi_min }}
          FILTER_RSI_MAX:    ${{ github.event.inputs.rsi_max }}
          FILTER_SLOPE_PCT:  ${{ github.event.inputs.slope_pct }}

          # Control
          DRY_RUN:           ${{ github.event.inputs.dry_run }}
          FORCE_RUN:         ${{ github.event.inputs.force_run }}
        run: |
          $SYMS = "${{ github.event.inputs.tickers }}"
          if ([string]::IsNullOrWhiteSpace($SYMS)) {
            & "$env:PYTHON_EXE" EMAMerged/scripts/live_paper_loop.py --config EMAMerged/config.yaml --tickers EMAMerged/tickers.txt --dry-run $env:DRY_RUN --force-run $env:FORCE_RUN
          } else {
            & "$env:PYTHON_EXE" EMAMerged/scripts/live_paper_loop.py --config EMAMerged/config.yaml --symbols "$SYMS" --dry-run $env:DRY_RUN --force-run $env:FORCE_RUN
          }
